// <auto-generated />
namespace PurdueIo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class BitwiseDOW : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BitwiseDOW));
        
        string IMigrationMetadata.Id
        {
            get { return "201410150206492_BitwiseDOW"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
